### PR TITLE
Add Uncapitalize so it supports pascal case. Closes #49

### LINKED ISSUE #49: Support pascal case to camel case?
Let's say that we have an object with this shape:

```typescript
const object = {
  'snake_field': 'snake',
  PascalField: 'pascal'
}
```

Right now, this returns the type:

```typescript
type Object = {
  snakeField: string,
  PascalField: string
}
```

I believe the type should be:

```typescript
type Object = {
  snakeField: string,
  pascalField: string
}
```

This is very easy to do, all we need is to change `CamelizeObject` to:

```typescript
type CamelizeObject<T, S = false> = {
  [K in keyof T as Uncapitalize<CamelCase<string & K>>]: T[K] extends Date
    ? T[K]
    : T[K] extends RegExp
    ? T[K]
    : T[K] extends Array<infer U>
    ? U extends {} | undefined
      ? Array<CamelizeObject<U>>
      : T[K]
    : T[K] extends {} | undefined
    ? S extends true
      ? T[K]
      : CamelizeObject<T[K]>
    : T[K];
};
```

The only thing that I changed, is that I added `Uncapitalize` before `CamelCase`. If this is fine, I can open a PR

### PR DESCRIPTION
**Pull request by ghmendonca**

### CODE REVIEW

**Comment by ghmendonca** [comment]
@jonkoops added tests and also changed the `walk` method to use the uncapitalized camel key

**Comment by kbrabrand** [comment]
> @kbrabrand do we want to put this behind a flag as an option, or should we bump the package a major version?

I'm thinking major version. Better not to have too many flags, and I also think peoples expectation is that it matches the behavior of `lodash.camelCase`.

**Review by jonkoops — APPROVED** [review]
LGTM

**Comment by ghmendonca** [comment]
@jonkoops @kbrabrand do you guys know when a new version will be published with these changes?

**Comment by kbrabrand** [comment]
Just noticed that @jonkoops merged it. Will get a new version out in an hour or two. Two kiddos need to go to bed first 😅

**Pull request merged**
